imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Wrk/wrk.yml
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.HttpClient/httpclient.yml
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

jobs:
  server:
    sources:
      crank:
        repository: https://github.com/mrsharm/crank
        branchOrCommit: test_wb 
    project: crank/samples/hello/hello.csproj
    #readyStateText: Application started.
    waitForExit: true

scenarios:
  hello:
    application:
      job: server
    # load:
    #   job: bombardier
    #   variables:
    #     serverPort: 5000
    #     path: /

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010
      load:
        endpoints: 
          - http://localhost:5010
